[project]
description = "The dependencies required to run the integration tests"
name = "serde-arrow"
version = "0.0.0"
requires-python = ">=3.12"

dependencies = [
    "pyarrow~=19.0",
    "numpy~=2.2",
    "ruff~=0.11",
    "polars~=1.25",
]

[tool.uv]
package = false
